# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 235be5ac3a40fe6a881ec61e085f8c9f12aed4f230ff691e66c91329da1f3777f02eb9ef6f3880b28a87701beed9cb54d3326df25a42bf2eae74485c852c372d

test:
  secret_key_base: 8cb4af2c4c772b89a30c25f5f2e164a0c93d2fb8d85b74c852d7ddf00ea755999b3695e621fd57e46d98052173fe4c23d2530852a1bf0b6302c262e458c194a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
